# Generated by Django 5.2.7 on 2025-10-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=40, unique=True)),
                ('serial_number', models.CharField(max_length=60, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CHECKED_OUT', 'Checked Out'), ('REPAIR', 'Repair'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
            ],
        ),
    ]
