# Generated by Django 5.2.7 on 2025-10-31 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_staff_student_alter_device_options_device_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='checkout',
            name='uniq_device_open_checkout',
        ),
        migrations.RemoveField(
            model_name='student',
            name='homeroom',
        ),
        migrations.AddField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='condition_in',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='condition_out',
            field=models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='main_app.device'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Operations', 'Operations'), ('IT', 'IT'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('device',), name='unique_open_checkout_per_device'),
        ),
    ]
