# Generated by Django 5.2.7 on 2025-11-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_staff_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='asset_tag',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
